name: auto

on:
  pull_request:
    types: [labeled]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: jacogr/action-merge@master
        with:
          checks: build,docs,lint,test
          labels: -auto
          strategy: squash
          token: ${{ secrets.GH_PAT_BOT }}
